CREATE TABLE IF NOT EXISTS `employee` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firstName` VARCHAR(255) NOT NULL,
  `middleName` VARCHAR(255) DEFAULT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(50) DEFAULT NULL,
  `sex` VARCHAR(50) DEFAULT NULL,
  `dateOfBirth` DATE DEFAULT NULL,
  `age` INT DEFAULT NULL,
  `educationLevel` VARCHAR(255) DEFAULT NULL,
  `qualificationYear` VARCHAR(50) DEFAULT NULL,
  `areaOfSpecialisation` VARCHAR(255) DEFAULT NULL,
  `ageRange` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL UNIQUE,
  `phone` VARCHAR(50) DEFAULT NULL,
  `locationType` VARCHAR(100) DEFAULT NULL,
  `province` VARCHAR(100) DEFAULT NULL,
  `district` VARCHAR(100) DEFAULT NULL,
  `cluster` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `grade` VARCHAR(100) DEFAULT NULL,
  `experienceYears` VARCHAR(100) DEFAULT NULL,
  `responses` JSON DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(50) DEFAULT 'USER',
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
